version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - attw
  - bumpp
  - crossws
  - eventa
  - listhen
  - taze
  - tsdown
  - unbird
  - moeru
  - unplugin
  - webworkers
ignoreWords: []
import: []
